[build]
  command = "npm run build"  # o el comando que usas para construir tu proyecto
  publish = "dist"          # la carpeta donde se encuentra la salida construida

[context.production.environment]
  NODE_VERSION = "14"        # la versión de Node.js que deseas utilizar en producción

[build.env.dependencies]
  @fullcalendar/core = "^6.1.10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200